server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


zuul:
  ignored-services: microservicecloud-dept
  #  设置统一公共前缀
  prefix: /gy
  #  原真实服务名忽略 忽略所有名字
  routes:
#    地址替换隐藏，隐藏了eureka上的服务id microservicecloud-dept替换为mydept
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**

info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

